<!doctype html public "-//W3C//DTD HTML 4.0 Transitional//EN">
theme: jekyll-theme-time-machine
<html><head>
<title> The College Cookbook </title>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=utf-8">
<body> 
<style>
 body {page-borders:"thick" canvas-style: "normal" header-subtitle:"address" banner-alignment:"center" height:100%;width:100%;background-image:url(1234.gif);background-repeat:no-repeat;background-size:cover;}
    img {border-radius: 50%;}
    h1 {color: #330000; text-align: center ; font-family: Acier BAT Text Noir ;font-size: 40px}
    p.ex1 {color: Black; text-align: left; font-family: Times New Roman; font-size: 20px; margin: 2cm 4cm 3cm 4cm;}
</style>
 <h1> Unsure</h1>
<div id="header_area" class="full_width">
<div class="page">
<ul class="menu">
<li class="tab tab-home"><a href="http://https://crypticalraisen.github.io/Website//">Home</a></li>
<li class="tab tab-1"><a href="http://https://crypticalraisen.github.io/Website//about-me/" title="About Me">About</a></li>
<li class="tab tab-2 current"><a href="https://crypticalraisen.github.io/Website//contact/" title="Get In Touch">Contact</a></li>
</ul>
<div id="header">
</div>
</div>
</div>
<div id="content_area" class="full_width">
<div class="page">
<div id="content_box">
<div id="content">

<div class="post_box top" id="post-32">
<div class="headline_area">
<h2>Welcome!</h2>
</div>
<div class="format_text">
<div class="wpcf7" id="wpcf7-f309-p32-o1" dir="ltr">
<div class="screen-reader-response"></div>
<p class="ex1"> This is absolutely strange to me. I've never attempted something like this before so, <em>buckle up</em>lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll.</p><br>
 
 
 
 
 
   
          
  
  <!-- You should go to Dave Raggett's page for help starting your webpage!!!-->
  <!-- http://www.w3.org/MarkUp/Guide/ -->

</body>

